-- Schema reconciliation: create objects that deployed trigger functions already
-- depend on but which no prior migration ever created. These existed on DEV
-- (added out-of-band) but never on prod, so prod carries live triggers that
-- reference missing objects:
--
--   1. audit_log — audit_row_change() does `insert into audit_log(...)` and is
--      wired as trg_audit_* on journeys, senders, suppressions, templates,
--      tenant_credentials, tenant_members, tenants. Without the table, ANY
--      write to those 7 tables errors ("relation audit_log does not exist").
--   2. tenant_invites.invited_by / tenant_members.invited_by —
--      consume_tenant_invites_on_signup() (trg_consume_invites on auth.users)
--      does `insert into tenant_members(..., invited_by) values (..., v_invite.invited_by)`.
--      Without the columns, every new-user signup errors.
--
-- Shapes are transcribed from the live DEV schema (the environment where these
-- objects already exist and the triggers work). All statements are idempotent.

-- 1. audit_log (append-only; no FKs so audit rows survive tenant/user deletion).
create table if not exists public.audit_log (
  id           bigint generated by default as identity primary key,
  at           timestamptz not null default now(),
  tenant_id    uuid,
  actor_id     uuid,
  actor_email  text,
  table_name   text not null,
  row_id       text,
  op           text not null check (op = any (array['INSERT','UPDATE','DELETE'])),
  before       jsonb,
  after        jsonb,
  changed_keys text[]
);

create index if not exists audit_log_tenant_at_idx on public.audit_log using btree (tenant_id, at desc);
create index if not exists audit_log_table_at_idx  on public.audit_log using btree (table_name, at desc);
create index if not exists audit_log_actor_at_idx  on public.audit_log using btree (actor_id, at desc);

alter table public.audit_log enable row level security;

-- Members of a tenant may read that tenant's audit rows (plus system rows where
-- tenant_id is null). Matches the DEV policy; the auth call is wrapped in a
-- scalar subselect for the init-plan performance fix.
drop policy if exists "audit_log_member_read" on public.audit_log;
create policy "audit_log_member_read" on public.audit_log
  as permissive for select to public
  using ((tenant_id is null) or (exists (
    select 1 from public.tenant_members m
     where m.tenant_id = audit_log.tenant_id
       and m.user_id = (select auth.uid())
  )));

-- 2. invited_by columns (nullable FK to auth.users; safe on empty tables).
alter table public.tenant_invites
  add column if not exists invited_by uuid references auth.users(id);
alter table public.tenant_members
  add column if not exists invited_by uuid references auth.users(id);
